-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghOhGjCgTNfiuuoRe
h3qKOmCgxfQ08++0YIIm2Hf3WRCgCgYIKoZIzj0DAQehRANCAASpsa4kA78ihxGG
j7oceNXSvzAyhpkB2G5ywsRzxQDgwGtUc8aHvGH0DpkanvBtlx7Wk2ehQwwrB4yM
3klShKwN
-----END PRIVATE KEY-----