//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try font.validate()
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 10 files.
  struct file {
    /// Resource file `Fameshow-1024.png`.
    static let fameshow1024Png = Rswift.FileResource(bundle: R.hostingBundle, name: "Fameshow-1024", pathExtension: "png")
    /// Resource file `Fameshow-120.png`.
    static let fameshow120Png = Rswift.FileResource(bundle: R.hostingBundle, name: "Fameshow-120", pathExtension: "png")
    /// Resource file `Fameshow-160.png`.
    static let fameshow160Png = Rswift.FileResource(bundle: R.hostingBundle, name: "Fameshow-160", pathExtension: "png")
    /// Resource file `Fameshow-40.png`.
    static let fameshow40Png = Rswift.FileResource(bundle: R.hostingBundle, name: "Fameshow-40", pathExtension: "png")
    /// Resource file `Fameshow-60.png`.
    static let fameshow60Png = Rswift.FileResource(bundle: R.hostingBundle, name: "Fameshow-60", pathExtension: "png")
    /// Resource file `Raleway-Regular.ttf`.
    static let ralewayRegularTtf = Rswift.FileResource(bundle: R.hostingBundle, name: "Raleway-Regular", pathExtension: "ttf")
    /// Resource file `default.png`.
    static let defaultPng = Rswift.FileResource(bundle: R.hostingBundle, name: "default", pathExtension: "png")
    /// Resource file `flip-icon-shadow.pdf`.
    static let flipIconShadowPdf = Rswift.FileResource(bundle: R.hostingBundle, name: "flip-icon-shadow", pathExtension: "pdf")
    /// Resource file `flip-icon.pdf`.
    static let flipIconPdf = Rswift.FileResource(bundle: R.hostingBundle, name: "flip-icon", pathExtension: "pdf")
    /// Resource file `star.pdf`.
    static let starPdf = Rswift.FileResource(bundle: R.hostingBundle, name: "star", pathExtension: "pdf")
    
    /// `bundle.url(forResource: "Fameshow-1024", withExtension: "png")`
    static func fameshow1024Png(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.fameshow1024Png
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Fameshow-120", withExtension: "png")`
    static func fameshow120Png(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.fameshow120Png
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Fameshow-160", withExtension: "png")`
    static func fameshow160Png(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.fameshow160Png
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Fameshow-40", withExtension: "png")`
    static func fameshow40Png(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.fameshow40Png
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Fameshow-60", withExtension: "png")`
    static func fameshow60Png(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.fameshow60Png
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "Raleway-Regular", withExtension: "ttf")`
    static func ralewayRegularTtf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ralewayRegularTtf
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "default", withExtension: "png")`
    static func defaultPng(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.defaultPng
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "flip-icon", withExtension: "pdf")`
    static func flipIconPdf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.flipIconPdf
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "flip-icon-shadow", withExtension: "pdf")`
    static func flipIconShadowPdf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.flipIconShadowPdf
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "star", withExtension: "pdf")`
    static func starPdf(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.starPdf
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 1 fonts.
  struct font: Rswift.Validatable {
    /// Font `Raleway-Regular`.
    static let ralewayRegular = Rswift.FontResource(fontName: "Raleway-Regular")
    
    /// `UIFont(name: "Raleway-Regular", size: ...)`
    static func ralewayRegular(size: CGFloat) -> UIKit.UIFont? {
      return UIKit.UIFont(resource: ralewayRegular, size: size)
    }
    
    static func validate() throws {
      if R.font.ralewayRegular(size: 42) == nil { throw Rswift.ValidationError(description:"[R.swift] Font 'Raleway-Regular' could not be loaded, is 'Raleway-Regular.ttf' added to the UIAppFonts array in this targets Info.plist?") }
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 16 images.
  struct image {
    /// Image `Fameshow-1024`.
    static let fameshow1024 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Fameshow-1024")
    /// Image `Fameshow-120`.
    static let fameshow120 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Fameshow-120")
    /// Image `Fameshow-160`.
    static let fameshow160 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Fameshow-160")
    /// Image `Fameshow-40`.
    static let fameshow40 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Fameshow-40")
    /// Image `Fameshow-60`.
    static let fameshow60 = Rswift.ImageResource(bundle: R.hostingBundle, name: "Fameshow-60")
    /// Image `default`.
    static let `default` = Rswift.ImageResource(bundle: R.hostingBundle, name: "default")
    /// Image `flip-icon`.
    static let flipIcon = Rswift.ImageResource(bundle: R.hostingBundle, name: "flip-icon")
    /// Image `gift-1`.
    static let gift1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "gift-1")
    /// Image `gift-2`.
    static let gift2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "gift-2")
    /// Image `gift-3`.
    static let gift3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "gift-3")
    /// Image `heart`.
    static let heart = Rswift.ImageResource(bundle: R.hostingBundle, name: "heart")
    /// Image `icon-close`.
    static let iconClose = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon-close")
    /// Image `icon-gift`.
    static let iconGift = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon-gift")
    /// Image `icon-like`.
    static let iconLike = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon-like")
    /// Image `person_small`.
    static let person_small = Rswift.ImageResource(bundle: R.hostingBundle, name: "person_small")
    /// Image `star`.
    static let star = Rswift.ImageResource(bundle: R.hostingBundle, name: "star")
    
    /// `UIImage(named: "Fameshow-1024", bundle: ..., traitCollection: ...)`
    static func fameshow1024(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fameshow1024, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Fameshow-120", bundle: ..., traitCollection: ...)`
    static func fameshow120(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fameshow120, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Fameshow-160", bundle: ..., traitCollection: ...)`
    static func fameshow160(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fameshow160, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Fameshow-40", bundle: ..., traitCollection: ...)`
    static func fameshow40(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fameshow40, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Fameshow-60", bundle: ..., traitCollection: ...)`
    static func fameshow60(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.fameshow60, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "default", bundle: ..., traitCollection: ...)`
    static func `default`(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.`default`, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "flip-icon", bundle: ..., traitCollection: ...)`
    static func flipIcon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.flipIcon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "gift-1", bundle: ..., traitCollection: ...)`
    static func gift1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gift1, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "gift-2", bundle: ..., traitCollection: ...)`
    static func gift2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gift2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "gift-3", bundle: ..., traitCollection: ...)`
    static func gift3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gift3, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "heart", bundle: ..., traitCollection: ...)`
    static func heart(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.heart, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon-close", bundle: ..., traitCollection: ...)`
    static func iconClose(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.iconClose, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon-gift", bundle: ..., traitCollection: ...)`
    static func iconGift(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.iconGift, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "icon-like", bundle: ..., traitCollection: ...)`
    static func iconLike(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.iconLike, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "person_small", bundle: ..., traitCollection: ...)`
    static func person_small(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.person_small, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "star", bundle: ..., traitCollection: ...)`
    static func star(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.star, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `GiftDisplayView`.
    static let giftDisplayView = _R.nib._GiftDisplayView()
    
    /// `UINib(name: "GiftDisplayView", in: bundle)`
    static func giftDisplayView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.giftDisplayView)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 2 view controllers.
  struct segue {
    /// This struct is generated for `AudienceViewController`, and contains static references to 1 segues.
    struct audienceViewController {
      /// Segue identifier `overlay`.
      static let overlay: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, AudienceViewController, LiveOverlayViewController> = Rswift.StoryboardSegueIdentifier(identifier: "overlay")
      
      /// Optionally returns a typed version of segue `overlay`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func overlay(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, AudienceViewController, LiveOverlayViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.audienceViewController.overlay, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `BroadcasterViewController`, and contains static references to 2 segues.
    struct broadcasterViewController {
      /// Segue identifier `overlay`.
      static let overlay: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, BroadcasterViewController, LiveOverlayViewController> = Rswift.StoryboardSegueIdentifier(identifier: "overlay")
      /// Segue identifier `upnext`.
      static let upnext: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, BroadcasterViewController, UpNextOverlayViewController> = Rswift.StoryboardSegueIdentifier(identifier: "upnext")
      
      /// Optionally returns a typed version of segue `overlay`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func overlay(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, BroadcasterViewController, LiveOverlayViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.broadcasterViewController.overlay, segue: segue)
      }
      
      /// Optionally returns a typed version of segue `upnext`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func upnext(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, BroadcasterViewController, UpNextOverlayViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.broadcasterViewController.upnext, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _GiftDisplayView.validate()
    }
    
    struct _GiftDisplayView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "GiftDisplayView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "gift-1", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'gift-1' is used in nib 'GiftDisplayView', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
      try launchScreen.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if UIKit.UIImage(named: "default.png") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'default.png' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = NavigationController
      
      let audience = StoryboardViewControllerResource<AudienceViewController>(identifier: "audience")
      let broadcast = StoryboardViewControllerResource<BroadcasterViewController>(identifier: "broadcast")
      let bundle = R.hostingBundle
      let email = StoryboardViewControllerResource<TextEntryViewController>(identifier: "email")
      let giftChooser = StoryboardViewControllerResource<GiftChooserViewController>(identifier: "giftChooser")
      let initial = StoryboardViewControllerResource<UIKit.UINavigationController>(identifier: "initial")
      let login = StoryboardViewControllerResource<TextEntryViewController>(identifier: "login")
      let masthead = StoryboardViewControllerResource<NavigationController>(identifier: "masthead")
      let name = "Main"
      let password = StoryboardViewControllerResource<TextEntryViewController>(identifier: "password")
      let push = StoryboardViewControllerResource<PushNotificationViewController>(identifier: "push")
      let up_next_overlay = StoryboardViewControllerResource<UpNextOverlayViewController>(identifier: "up_next_overlay")
      let username = StoryboardViewControllerResource<TextEntryViewController>(identifier: "username")
      
      func audience(_: Void = ()) -> AudienceViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: audience)
      }
      
      func broadcast(_: Void = ()) -> BroadcasterViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: broadcast)
      }
      
      func email(_: Void = ()) -> TextEntryViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: email)
      }
      
      func giftChooser(_: Void = ()) -> GiftChooserViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: giftChooser)
      }
      
      func initial(_: Void = ()) -> UIKit.UINavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: initial)
      }
      
      func login(_: Void = ()) -> TextEntryViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: login)
      }
      
      func masthead(_: Void = ()) -> NavigationController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: masthead)
      }
      
      func password(_: Void = ()) -> TextEntryViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: password)
      }
      
      func push(_: Void = ()) -> PushNotificationViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: push)
      }
      
      func up_next_overlay(_: Void = ()) -> UpNextOverlayViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: up_next_overlay)
      }
      
      func username(_: Void = ()) -> TextEntryViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: username)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "gift-3") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'gift-3' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "person_small") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'person_small' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "flip-icon") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'flip-icon' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "gift-1") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'gift-1' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "gift-2") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'gift-2' is used in storyboard 'Main', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon-like") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon-like' is used in storyboard 'Main', but couldn't be loaded.") }
        if _R.storyboard.main().giftChooser() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'giftChooser' could not be loaded from storyboard 'Main' as 'GiftChooserViewController'.") }
        if _R.storyboard.main().login() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'login' could not be loaded from storyboard 'Main' as 'TextEntryViewController'.") }
        if _R.storyboard.main().email() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'email' could not be loaded from storyboard 'Main' as 'TextEntryViewController'.") }
        if _R.storyboard.main().push() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'push' could not be loaded from storyboard 'Main' as 'PushNotificationViewController'.") }
        if _R.storyboard.main().audience() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'audience' could not be loaded from storyboard 'Main' as 'AudienceViewController'.") }
        if _R.storyboard.main().up_next_overlay() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'up_next_overlay' could not be loaded from storyboard 'Main' as 'UpNextOverlayViewController'.") }
        if _R.storyboard.main().broadcast() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'broadcast' could not be loaded from storyboard 'Main' as 'BroadcasterViewController'.") }
        if _R.storyboard.main().password() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'password' could not be loaded from storyboard 'Main' as 'TextEntryViewController'.") }
        if _R.storyboard.main().initial() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'initial' could not be loaded from storyboard 'Main' as 'UIKit.UINavigationController'.") }
        if _R.storyboard.main().masthead() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'masthead' could not be loaded from storyboard 'Main' as 'NavigationController'.") }
        if _R.storyboard.main().username() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'username' could not be loaded from storyboard 'Main' as 'TextEntryViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
